[workspace]
resolver = "2"
members = [
    "cli",
    "crd-templator",
    "defs",
    "env_aws",
    "env_aws_direct",
    "env_azure",
    "env_azure_direct",
    "env_common",
    "gitops",
    "infraweave_py",
    "infraweave-mcp",
    "operator",
    "prometheus_exporter",
    "reconciler",
    "terraform_runner",
    "utils",
    "webserver-openapi",
    "integration-tests",
    "graph",
    "catalog/catalog-trait",
    "catalog/catalog-aws-apigw",
    "catalog/catalog-aws",
    "catalog/catalog-http",
    "catalog/catalog-mem",
    "catalog/catalog-client",
    "catalog/catalog-client-aws-http",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
warnings = "deny"

[workspace.dependencies]
testcontainers = "0.27.1"
testcontainers-modules = "0.15.0"
bollard = "0.20.1"
mockall = "0.13"
anyhow = "1.0"
async-trait = "0.1.50"

[profile.ci-tests]
inherits = "test"
debug = 1
incremental = false
opt-level = 1
split-debuginfo = "packed"
